add meta description
Antolius/deployments-and-disasters pull request #4
Opened 2020-12-23 20:15 UTC by lpmi-13

this helps SEO and allows other people to find this awesome resource easier.

2020-12-23 20:16 UTC, lpmi-13 commented
for reference, here's the current lighthouse audit

![lighthouse - seo](https://user-images.githubusercontent.com/5070516/103033959-b53dd180-455b-11eb-9d32-87493b3bd912.png)

2021-01-01 18:28 UTC, Antolius requested changes
This is a good idea! I'd just suggest a bit different approach to implementation.
If you are still up for it I'll leave it for you to update the PR.
If you don't have the time right now I can take it over myself.

2021-01-01 18:28 UTC, Antolius commented on layouts/partials/site/meta.html
> +<meta name="description" content="A tabletop RPG for practicing incident management">
Nice catch, but I'd suggest a slightly different solution:

There's already a description meta tag defined 2 lines down. It's set up to render the `description` variable of each individual page, which in turn can be defined alongside title and other [front matter variables](https://gohugo.io/content-management/front-matter#predefined). Unfortunately I completely forgot about this once I got to writing the site content, so the `.Description` variable is always empty and the description tag is skipped.

I still like the idea of defining unique description for each page. However, it also makes sense to have a default value here in the meantime (and in case some page still ends up missing it). You should be able to achieve this by piping to the [default function](https://gohugo.io/functions/default/) in the expression on the line below:
```{{ with .Description | default "A tabletop RPG for practicing incident management." }}```

2021-01-01 19:18 UTC, lpmi-13 commented on layouts/partials/site/meta.html
> +<meta name="description" content="A tabletop RPG for practicing incident management">
Ah right...I keep forgetting how hugo likes to do templating and variables and such. I had to update another PR I did for a different project in this same exact manner a few months back, so I  an handle this myself, no worries.

2021-01-02 19:39 UTC, lpmi-13 commented
Updated the default description in the actual way Hugo expects it (ha), and also made a first attempt at adding specific descriptions to each page. It's very likely I misunderstood the intent of some of the pages, so feel free to edit those directly, or lemme know which changes would be nice and I can do it myself.

2021-01-02 19:41 UTC, lpmi-13 commented
ah, wait a sec...just managed to get the old commit for typo stuff mangled in with this PR...lemme fix that real quick.

2021-01-02 19:45 UTC, lpmi-13 commented
tried to be polite and do it without a rebase and force push, but didn't seem to be working, and I doubt you had based any work off this branch anyway, so all sorted now.

2021-01-02 19:45 UTC, lpmi-13 commented on layouts/partials/site/meta.html
> +<meta name="description" content="A tabletop RPG for practicing incident management">
all sorted now

2021-01-12 22:30 UTC, Antolius commented
This is great content! Thank you for adding individual descriptions, I'll merge them as is. They can be fine-tuned later on.

2021-01-12 22:31 UTC, merged